# Grafana Datasource Provisioning - PostgreSQL
apiVersion: 1

datasources:
  - name: CloudSecurityDB
    type: postgres
    url: postgresql:5432
    database: ${POSTGRES_DB:-security_audits}
    user: ${POSTGRES_USER:-auditor}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-changeme}
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: false
